"""Real-world usability check: live data, never-seen-during-training queries.

Every prior verification (`train_*.py`'s test_heldout, `verify_package.py`)
used data drawn from the same generation process as training, even when the
split held out template families or districts. This script is different on
purpose: it hits live external APIs at request time (today's actual forecast,
not anything cached or templated) and feeds M3 genuinely hand-written queries
that were never run through the D4 template/translation pipeline at all —
casual phrasing, typos, code-switching mid-sentence, incomplete questions,
and out-of-domain questions a real user would also type.

This is not a benchmark and is not scored against a labelled gold set (there
is no ground truth for "did the model rank sources correctly for a query
nobody labelled") — it's a smoke test for whether the shipped package holds
up outside the shape of its own training/eval data, run once and read by a
human, not gated automatically.
"""
from __future__ import annotations

import json

from modal_jobs.common import DATA_DIR, MODEL_DIR, TRAIN_IMAGE, TRAIN_VOLUMES, app

# Mix of training-set-style districts and genuinely smaller/less common towns,
# spanning coastal, inland, hill and arid regions -- not curated to be easy.
LIVE_LOCATIONS = [
    {"name": "Puri", "lat": 19.8134, "lon": 85.8315, "elevation_m": 2.0},
    {"name": "Coimbatore", "lat": 11.0168, "lon": 76.9558, "elevation_m": 411.0},
    {"name": "Bikaner", "lat": 28.0229, "lon": 73.3119, "elevation_m": 234.0},
    {"name": "Shillong", "lat": 25.5788, "lon": 91.8933, "elevation_m": 1496.0},
    {"name": "Rajahmundry", "lat": 16.9891, "lon": 81.7828, "elevation_m": 46.0},
]

MODELS = ["gfs_seamless", "ecmwf_ifs025", "icon_seamless", "gem_seamless"]

# Genuinely never generated by build_queries.py -- real phrasing, typos,
# code-switching, incomplete sentences, and a few out-of-domain questions to
# see how gracefully the system fails rather than fabricating an answer.
REAL_QUERIES = [
    "is it gonna rain today in puri or what",
    "mausam kaisa rahega kal Coimbatore mein subah subah",
    "bikaner mein itni garmi kab tak rahegi",
    "should i take umbrella tmrw morning shillong",
    "rajahmundry weather rn",
    "எப்போ மழை பெய்யும் கோயம்புத்தூரில்",  # Tamil: "when will it rain in Coimbatore"
    "will there b flood risk near puri this wknd due to the cyclone",
    "what's the capital of odisha",  # out-of-domain, should not fabricate weather
    "பயிருக்கு தண்ணீர் விட வேண்டுமா இன்று",  # Tamil: should I irrigate my crop today
    "storm coming???",
    "hey can u tell me if its safe for boats near puri tomorow morning",
    "mera cotton ka fasal kharab ho jayega kya is baarish se bikaner me",
]

SAMPLE_FIELD_NAMES_LIVE_STYLE = [
    # Not from D3's training tables -- deliberately obscure/realistic strings
    # a real provider integration would actually hand the mapper.
    ("2t", "K", "2 metre temperature", "surface", "instant"),
    ("tp", "m", "Total precipitation", "surface", "0-24h accumulated"),
    ("10si", "m s**-1", "10 metre wind speed", "surface", "instant"),
    ("VIS", "m", "Visibility", "surface", ""),
    ("CAPE_180-0mb", "J kg-1", "Convective available potential energy", "180-0 mb above ground", ""),
    ("PWAT_entire_atmosphere", "kg m-2", "Precipitable water", "entire atmosphere", ""),
]


@app.function(image=TRAIN_IMAGE, volumes=TRAIN_VOLUMES, timeout=60 * 10)
def check() -> dict:
    import httpx

    from weathergpt_models import ModelRegistry

    registry = ModelRegistry.from_dir(MODEL_DIR)
    report: dict = {"status": registry.status(), "sections": {}}

    # ---- 1. live multi-model forecast + M2 correction -----------------------
    live_forecasts = []
    with httpx.Client(timeout=30.0) as client:
        for loc in LIVE_LOCATIONS:
            resp = client.get("https://api.open-meteo.com/v1/forecast", params={
                "latitude": loc["lat"], "longitude": loc["lon"],
                "models": ",".join(MODELS),
                "hourly": "temperature_2m,precipitation,wind_speed_10m",
                "forecast_days": 1, "timezone": "UTC",
            })
            resp.raise_for_status()
            data = resp.json()
            hour_idx = 12  # midday UTC
            row = {"location": loc["name"]}
            for var in ("temperature_2m", "precipitation", "wind_speed_10m"):
                per_model = {}
                for m in MODELS:
                    key = f"{var}_{m}"
                    series = data.get("hourly", {}).get(key)
                    if series and hour_idx < len(series) and series[hour_idx] is not None:
                        per_model[m] = series[hour_idx]
                if len(per_model) >= 2:
                    row[var] = per_model
            live_forecasts.append(row)
    report["sections"]["live_fetch"] = {
        "note": "fetched live from api.open-meteo.com/v1/forecast at request time, "
               "today's actual multi-model forecast, not cached/templated data",
        "locations": [r["location"] for r in live_forecasts],
        "raw": live_forecasts,
    }

    mos_results = []
    if registry.mos is not None:
        for row, loc in zip(live_forecasts, LIVE_LOCATIONS):
            for var, forecasts in row.items():
                if var == "location" or not registry.mos.supports(
                        {"temperature_2m": "temperature_2m", "precipitation": "precipitation",
                         "wind_speed_10m": "wind_speed_10m"}.get(var, var)):
                    continue
                try:
                    corrected = registry.mos.correct(var, forecasts=forecasts, context={
                        "lead_hours": 12, "lead_age_days": 0, "hour_utc": 12, "doy": 247,
                        "elevation_m": loc["elevation_m"], "lat": loc["lat"], "lon": loc["lon"],
                    })
                    mos_results.append({
                        "location": loc["name"], "variable": var,
                        "raw_mean": sum(forecasts.values()) / len(forecasts),
                        "corrected": corrected.value,
                        "interval_80": [corrected.interval_low, corrected.interval_high],
                    })
                except Exception as exc:
                    mos_results.append({"location": loc["name"], "variable": var,
                                        "error": str(exc)})
    report["sections"]["m2_mos_on_live_data"] = mos_results

    # ---- 2. M4 calibration on the same live multi-model forecast -------------
    # M4's trained interface is the 4-member multi-model spread (same shape M2
    # consumes), not the 31-member raw GFS ensemble -- see
    # registry.calibration.transfer_assumption for why those are compatible at
    # the summary-statistic level. Reuse the live fetch from section 1.
    calib_results = []
    if registry.calibration is not None:
        for row, loc in zip(live_forecasts, LIVE_LOCATIONS):
            forecasts = row.get("precipitation")
            if not forecasts or len(forecasts) < 2:
                continue
            try:
                curve = registry.calibration.probability_curve(
                    "precipitation", forecasts=forecasts, context={
                        "lead_hours": 12, "lead_age_days": 0, "hour_utc": 12,
                        "doy": 247, "elevation_m": loc["elevation_m"],
                        "lat": loc["lat"], "lon": loc["lon"]},
                    other_forecasts={k: v for k, v in row.items()
                                     if k not in ("location", "precipitation")})
                calib_results.append({
                    "location": loc["name"],
                    "raw_multi_model_forecast_mm": forecasts,
                    "calibrated_curve": [
                        {"threshold_mm": c.threshold, "probability": round(c.probability, 4),
                         "raw_ensemble_frequency": round(c.raw_ensemble_frequency, 4)}
                        for c in curve],
                })
            except Exception as exc:
                calib_results.append({"location": loc["name"], "error": str(exc)})
    report["sections"]["m4_calibration_on_live_data"] = calib_results

    # ---- 3. M5 ranking on the live multi-model spread ------------------------
    rank_results = []
    if registry.trust_ranker is not None:
        for row, loc in zip(live_forecasts, LIVE_LOCATIONS):
            for var, forecasts in row.items():
                if var == "location":
                    continue
                canon = {"temperature_2m": "temperature_2m", "precipitation": "precipitation_amount",
                        "wind_speed_10m": "wind_speed_10m"}.get(var, var)
                if not registry.trust_ranker.supports(canon):
                    continue
                try:
                    ranked = registry.trust_ranker.rank(canon, candidates=forecasts, context={
                        "lead_hours": 12, "season": "autumn", "elevation_m": loc["elevation_m"],
                        "lat": loc["lat"], "lon": loc["lon"]})
                    rank_results.append({"location": loc["name"], "variable": canon,
                                         "order": [r.source for r in ranked]})
                except Exception as exc:
                    rank_results.append({"location": loc["name"], "variable": canon,
                                         "error": str(exc)})
    report["sections"]["m5_ranking_on_live_data"] = rank_results

    # ---- 4. M3 on genuinely novel, never-templated queries --------------------
    intent_results = []
    if registry.intent is not None:
        for query in REAL_QUERIES:
            try:
                parsed = registry.intent.parse(query)
                intent_results.append({
                    "query": query, "intent": parsed.intent,
                    "confidence": round(parsed.intent_confidence, 3),
                    "location_span": parsed.slot_text("LOC"),
                    "time_span": parsed.slot_text("TIME"),
                    "variables_note": "not used downstream; documented weak head",
                })
            except Exception as exc:
                intent_results.append({"query": query, "error": str(exc)})
    report["sections"]["m3_on_never_seen_queries"] = intent_results

    # ---- 5. M1 on realistic-but-unseen field name strings ---------------------
    field_results = []
    if registry.field_mapper is not None:
        for name, unit, desc, level, trange in SAMPLE_FIELD_NAMES_LIVE_STYLE:
            try:
                mapping = registry.field_mapper.map_field(name, unit=unit, description=desc)
                field_results.append({
                    "raw_field": name, "unit": unit,
                    "mapped_to": mapping.canonical_variable if mapping.is_usable else "ABSTAIN",
                    "confidence": round(mapping.confidence, 3),
                })
            except Exception as exc:
                field_results.append({"raw_field": name, "error": str(exc)})
    report["sections"]["m1_on_unseen_field_names"] = field_results

    with open(f"{DATA_DIR}/realworld_check_report.json", "w") as handle:
        json.dump(report, handle, indent=2, default=str)
    from modal_jobs.common import DATA_VOL
    DATA_VOL.commit()
    print(f"[realworld_check] wrote {DATA_DIR}/realworld_check_report.json")
    print(json.dumps(report["sections"]["m3_on_never_seen_queries"], indent=2, default=str))
    print(json.dumps(report["sections"]["m1_on_unseen_field_names"], indent=2, default=str))
    return report


@app.local_entrypoint()
def main_realworld_check():
    check.remote()
